services:
    mybundle.tblprefix_subscriber:
        class: Fc\FantaBundle\Subscriber\TablePrefixSubscriber
        arguments: [%fc_fanta.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }