FcFantaBundle:
    resource: "@FcFantaBundle/Controller/"
    type:     annotation
    prefix:   /fanta

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
