FcTeam:
    type: entity
    table: fc_team
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
    manyToOne:
        season:
            targetEntity: Season
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                season_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
