<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120728175517 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fc_League ADD enabled TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE fc_Championship ADD enabled TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE fc_Competition ADD enabled TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fc_Championship DROP enabled");
        $this->addSql("ALTER TABLE fc_Competition DROP enabled");
        $this->addSql("ALTER TABLE fc_League DROP enabled");
    }
}
