<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120731165413 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fc2_signing ADD day_id INT DEFAULT NULL, ADD club_id INT DEFAULT NULL, ADD player_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE fc2_signing ADD CONSTRAINT FK_C7749F729C24126 FOREIGN KEY (day_id) REFERENCES fc2_Day (id)");
        $this->addSql("ALTER TABLE fc2_signing ADD CONSTRAINT FK_C7749F7261190A32 FOREIGN KEY (club_id) REFERENCES fc2_Club (id)");
        $this->addSql("ALTER TABLE fc2_signing ADD CONSTRAINT FK_C7749F7299E6F5DF FOREIGN KEY (player_id) REFERENCES fc2_Player (id)");
        $this->addSql("CREATE INDEX IDX_C7749F729C24126 ON fc2_signing (day_id)");
        $this->addSql("CREATE INDEX IDX_C7749F7261190A32 ON fc2_signing (club_id)");
        $this->addSql("CREATE INDEX IDX_C7749F7299E6F5DF ON fc2_signing (player_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE fc2_Signing DROP FOREIGN KEY FK_C7749F729C24126");
        $this->addSql("ALTER TABLE fc2_Signing DROP FOREIGN KEY FK_C7749F7261190A32");
        $this->addSql("ALTER TABLE fc2_Signing DROP FOREIGN KEY FK_C7749F7299E6F5DF");
        $this->addSql("DROP INDEX IDX_C7749F729C24126 ON fc2_Signing");
        $this->addSql("DROP INDEX IDX_C7749F7261190A32 ON fc2_Signing");
        $this->addSql("DROP INDEX IDX_C7749F7299E6F5DF ON fc2_Signing");
        $this->addSql("ALTER TABLE fc2_Signing DROP day_id, DROP club_id, DROP player_id");
    }
}
